CREATE OR REPLACE PROCEDURE PDM_DEMO.APP.RESET_DEMO()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    DELETE FROM PDM_DEMO.APP.TECH_SCHEDULES WHERE IS_BASELINE = FALSE;
    DELETE FROM PDM_DEMO.APP.WORK_ORDERS 
    WHERE STATUS = 'SCHEDULED' AND SCHEDULED_DATE IS NOT NULL
      AND WO_ID NOT IN (
        SELECT WO_ID FROM PDM_DEMO.APP.WORK_ORDERS 
        WHERE DESCRIPTION LIKE 'Scheduled PM%' 
           OR DESCRIPTION LIKE 'Emergency%' 
           OR DESCRIPTION LIKE 'Routine%' 
           OR DESCRIPTION LIKE 'Compressor oil%'
      );
    RETURN 'Demo reset complete. Cleared non-baseline schedules and bundled work orders.';
END;
$$;

GRANT USAGE ON PROCEDURE PDM_DEMO.APP.RESET_DEMO() TO ROLE DEMO_PDM_ADMIN;
