-- ============================================================================
-- Midstream Predictive Maintenance Demo - Snowflake Setup
-- ============================================================================
-- Run with ACCOUNTADMIN (demo accounts) or a role with CREATE DATABASE privilege.
-- For production-like setup, use the DEMO_PDM_ADMIN role created below.
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- ----------------------------------------------------------------------------
-- 1. Warehouse
-- ----------------------------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS PDM_DEMO_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- ----------------------------------------------------------------------------
-- 2. Database and Schemas
-- ----------------------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS PDM_DEMO;

CREATE SCHEMA IF NOT EXISTS PDM_DEMO.RAW;
CREATE SCHEMA IF NOT EXISTS PDM_DEMO.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS PDM_DEMO.ML;
CREATE SCHEMA IF NOT EXISTS PDM_DEMO.APP;

USE DATABASE PDM_DEMO;
USE WAREHOUSE PDM_DEMO_WH;

-- ----------------------------------------------------------------------------
-- 3. Core Tables (RAW schema)
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TABLE RAW.STATIONS (
    STATION_ID      INT PRIMARY KEY,
    NAME            VARCHAR(100) NOT NULL,
    LAT             FLOAT NOT NULL,
    LON             FLOAT NOT NULL,
    REGION          VARCHAR(50),
    STATION_TYPE    VARCHAR(50)
);

CREATE OR REPLACE TABLE RAW.ASSETS (
    ASSET_ID        INT PRIMARY KEY,
    STATION_ID      INT NOT NULL REFERENCES RAW.STATIONS(STATION_ID),
    ASSET_TYPE      VARCHAR(20) NOT NULL,  -- PUMP | COMPRESSOR
    MODEL_NAME      VARCHAR(100),
    MANUFACTURER    VARCHAR(100),
    INSTALL_DATE    DATE,
    RATED_CAPACITY  FLOAT,
    ATTRIBUTES      VARIANT
);

CREATE OR REPLACE TABLE RAW.PUMP_TELEMETRY (
    PUMP_ID             INT NOT NULL,
    TS                  TIMESTAMP_NTZ NOT NULL,
    SUCTION_PRESSURE    FLOAT,
    DISCHARGE_PRESSURE  FLOAT,
    FLOW_RATE           FLOAT,
    MOTOR_CURRENT       FLOAT,
    PUMP_SPEED          FLOAT,
    BEARING_TEMP        FLOAT,
    CASING_TEMP         FLOAT,
    VIBRATION_RMS       FLOAT,
    VALVE_POSITION      FLOAT,
    LEAK_RATE           FLOAT
);

CREATE OR REPLACE VIEW RAW.TELEMETRY AS
SELECT
    PUMP_ID AS ASSET_ID,
    TS,
    VIBRATION_RMS AS VIBRATION,
    BEARING_TEMP AS TEMPERATURE,
    DISCHARGE_PRESSURE AS PRESSURE,
    FLOW_RATE,
    PUMP_SPEED AS RPM,
    MOTOR_CURRENT / 5 AS OIL_PRESSURE,
    MOTOR_CURRENT AS POWER_DRAW,
    DISCHARGE_PRESSURE - SUCTION_PRESSURE AS DIFFERENTIAL_PRESSURE,
    DISCHARGE_PRESSURE / NULLIF(SUCTION_PRESSURE, 0) AS COMPRESSION_RATIO,
    SUCTION_PRESSURE,
    CASING_TEMP AS SEAL_TEMPERATURE,
    LEAK_RATE AS CAVITATION_INDEX,
    CASING_TEMP AS DISCHARGE_TEMP,
    BEARING_TEMP - 40 AS INLET_TEMP
FROM PDM_DEMO.RAW.PUMP_TELEMETRY;

CREATE OR REPLACE TABLE RAW.MAINTENANCE_LOGS (
    LOG_ID          INT PRIMARY KEY AUTOINCREMENT,
    ASSET_ID        INT NOT NULL REFERENCES RAW.ASSETS(ASSET_ID),
    TS              TIMESTAMP_NTZ NOT NULL,
    MAINTENANCE_TYPE VARCHAR(50),
    DESCRIPTION     VARCHAR(2000),
    TECHNICIAN_ID   VARCHAR(20),
    PARTS_USED      VARIANT,
    DURATION_HRS    FLOAT,
    COST            FLOAT
);

CREATE OR REPLACE TABLE RAW.PARTS_INVENTORY (
    PART_ID         INT PRIMARY KEY,
    PART_NAME       VARCHAR(200) NOT NULL,
    ASSET_TYPE      VARCHAR(20),
    CATEGORY        VARCHAR(50),
    UNIT_COST       FLOAT,
    QTY_ON_HAND     INT,
    LEAD_TIME_DAYS  INT
);

CREATE OR REPLACE TABLE RAW.TECHNICIANS (
    TECH_ID             VARCHAR(20) PRIMARY KEY,
    NAME                VARCHAR(100) NOT NULL,
    HOME_BASE_LAT       FLOAT,
    HOME_BASE_LON       FLOAT,
    HOME_BASE_CITY      VARCHAR(100),
    CERTIFICATIONS      VARIANT,
    AVAILABILITY        VARCHAR(20) DEFAULT 'AVAILABLE',
    YEARS_EXPERIENCE    INT,
    SPECIALTY_NOTES     VARCHAR(500),
    BIO                 VARCHAR(2000),
    PHOTO_URL           VARCHAR(1000),
    HOURLY_RATE         FLOAT
);

-- ----------------------------------------------------------------------------
-- 4. Analytics Tables
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TABLE ANALYTICS.FEATURE_STORE (
    ASSET_ID                INT NOT NULL,
    AS_OF_TS                TIMESTAMP_NTZ NOT NULL,
    ASSET_TYPE              VARCHAR(20),
    VIBRATION_MEAN_24H      FLOAT,
    VIBRATION_STD_24H       FLOAT,
    VIBRATION_MAX_24H       FLOAT,
    VIBRATION_TREND         FLOAT,
    TEMPERATURE_MEAN_24H    FLOAT,
    TEMPERATURE_STD_24H     FLOAT,
    TEMPERATURE_MAX_24H     FLOAT,
    TEMPERATURE_TREND       FLOAT,
    PRESSURE_MEAN_24H       FLOAT,
    PRESSURE_STD_24H        FLOAT,
    FLOW_RATE_MEAN_24H      FLOAT,
    RPM_MEAN_24H            FLOAT,
    RPM_STD_24H             FLOAT,
    POWER_DRAW_MEAN_24H     FLOAT,
    DIFF_PRESSURE_MEAN_24H  FLOAT,
    SEAL_TEMP_MEAN_24H      FLOAT,
    DISCHARGE_TEMP_MEAN_24H FLOAT,
    COMPRESSION_RATIO_MEAN  FLOAT,
    OIL_PRESSURE_MEAN_24H   FLOAT,
    DAYS_SINCE_MAINTENANCE  INT,
    MAINTENANCE_COUNT_90D   INT,
    OPERATING_HOURS         FLOAT,
    FAILURE_LABEL           VARCHAR(30),
    DAYS_TO_FAILURE         FLOAT
);

CREATE OR REPLACE TABLE ANALYTICS.PREDICTIONS (
    PUMP_ID             INT NOT NULL,
    TS                  TIMESTAMP_NTZ NOT NULL,
    PREDICTED_CLASS     VARCHAR(30),
    PREDICTED_RUL_DAYS  FLOAT,
    CONFIDENCE          FLOAT,
    TOP_FEATURE         VARCHAR(100)
);

CREATE OR REPLACE TABLE ANALYTICS.DATA_NOW_TS (
    NOW_TS TIMESTAMP_NTZ DEFAULT '2026-03-17 23:55:00'::TIMESTAMP_NTZ
);
INSERT INTO ANALYTICS.DATA_NOW_TS (NOW_TS) VALUES ('2026-03-17 23:55:00'::TIMESTAMP_NTZ);

-- ----------------------------------------------------------------------------
-- 4b. ML Tables
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TABLE ML.MODEL_METADATA (
    KEY         VARCHAR(100) PRIMARY KEY,
    VALUE       VARCHAR(16000),
    UPDATED_AT  TIMESTAMP_NTZ
);

-- ----------------------------------------------------------------------------
-- 5. APP Tables
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TABLE APP.MANUALS (
    DOC_ID          INT PRIMARY KEY,
    ASSET_TYPE      VARCHAR(20),
    MODEL_NAME      VARCHAR(100),
    SECTION_TYPE    VARCHAR(50),
    TITLE           VARCHAR(500),
    CONTENT         VARCHAR(16000),
    SOURCE_URL      VARCHAR(1000)
);

CREATE OR REPLACE TABLE APP.WORK_ORDERS (
    WO_ID           INT PRIMARY KEY AUTOINCREMENT,
    ASSET_ID        INT NOT NULL,
    TECH_ID         VARCHAR(20),
    PRIORITY        VARCHAR(20),
    DESCRIPTION     VARCHAR(2000),
    PARTS_NEEDED    VARIANT,
    STATUS          VARCHAR(20) DEFAULT 'OPEN',
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SCHEDULED_DATE  DATE,
    ESTIMATED_HOURS FLOAT,
    STATION_NAME    VARCHAR(200)
);

CREATE OR REPLACE TABLE APP.TECH_SCHEDULES (
    SCHEDULE_ID     INT PRIMARY KEY AUTOINCREMENT,
    TECH_ID         VARCHAR(20) NOT NULL,
    SCHEDULE_DATE   DATE NOT NULL,
    BLOCK_TYPE      VARCHAR(20) DEFAULT 'WORK_ORDER',
    WO_ID           INT,
    ASSET_ID        INT,
    STATION_NAME    VARCHAR(200),
    ESTIMATED_HOURS FLOAT DEFAULT 4,
    NOTES           VARCHAR(500),
    IS_BASELINE     BOOLEAN DEFAULT FALSE,
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ----------------------------------------------------------------------------
-- 6. Fleet KPI View (used by Cortex Analyst)
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW ANALYTICS.FLEET_KPI_VIEW AS
WITH latest_predictions AS (
    SELECT 
        PUMP_ID AS ASSET_ID,
        TS AS AS_OF_TS,
        PREDICTED_CLASS,
        PREDICTED_RUL_DAYS,
        CONFIDENCE,
        TOP_FEATURE,
        CASE 
            WHEN PREDICTED_CLASS = 'OFFLINE' THEN 'FAILED'
            WHEN PREDICTED_CLASS = 'NORMAL' THEN 'HEALTHY'
            WHEN PREDICTED_RUL_DAYS IS NULL THEN 'HEALTHY'
            WHEN PREDICTED_RUL_DAYS <= 7 THEN 'CRITICAL'
            WHEN PREDICTED_RUL_DAYS <= 14 THEN 'WARNING'
            ELSE 'HEALTHY'
        END AS RISK_LEVEL
    FROM ANALYTICS.PREDICTIONS
    QUALIFY ROW_NUMBER() OVER (PARTITION BY PUMP_ID ORDER BY TS DESC) = 1
),
latest_maintenance AS (
    SELECT
        ASSET_ID,
        MAX(TS) AS LAST_MAINTENANCE_DATE,
        COUNT(*) AS TOTAL_MAINTENANCE_COUNT
    FROM RAW.MAINTENANCE_LOGS
    GROUP BY ASSET_ID
)
SELECT
    a.ASSET_ID,
    a.ASSET_TYPE,
    a.MODEL_NAME,
    a.MANUFACTURER,
    a.INSTALL_DATE,
    a.RATED_CAPACITY,
    s.STATION_ID,
    s.NAME AS STATION_NAME,
    s.LAT AS STATION_LAT,
    s.LON AS STATION_LON,
    s.REGION,
    p.PREDICTED_CLASS,
    p.PREDICTED_RUL_DAYS,
    p.RISK_LEVEL,
    p.AS_OF_TS AS PREDICTION_TS,
    m.LAST_MAINTENANCE_DATE,
    DATEDIFF('day', m.LAST_MAINTENANCE_DATE, CURRENT_TIMESTAMP()) AS DAYS_SINCE_MAINTENANCE,
    m.TOTAL_MAINTENANCE_COUNT
FROM RAW.ASSETS a
JOIN RAW.STATIONS s ON a.STATION_ID = s.STATION_ID
LEFT JOIN latest_predictions p ON a.ASSET_ID = p.ASSET_ID
LEFT JOIN latest_maintenance m ON a.ASSET_ID = m.ASSET_ID;

-- ----------------------------------------------------------------------------
-- 7. Stage for semantic model and manuals
-- ----------------------------------------------------------------------------
CREATE STAGE IF NOT EXISTS APP.MODELS
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE STAGE IF NOT EXISTS APP.DATA_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE STAGE IF NOT EXISTS APP.SPECS
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- ----------------------------------------------------------------------------
-- 8. SPCS Infrastructure (placeholders - deploy_spcs.sh fills values)
-- ----------------------------------------------------------------------------
CREATE IMAGE REPOSITORY IF NOT EXISTS APP.PDM_REPO;

-- Secrets (PAT and private key will be populated during deployment)
-- CREATE OR REPLACE SECRET APP.PAT_SECRET
--   TYPE = GENERIC_STRING
--   SECRET_STRING = '<REPLACE>';
--
-- CREATE OR REPLACE SECRET APP.PRIVATE_KEY_SECRET
--   TYPE = GENERIC_STRING
--   SECRET_STRING = '<REPLACE>';

-- ----------------------------------------------------------------------------
-- 9. Demo Role (recommended safer path)
-- ----------------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS DEMO_PDM_ADMIN;
GRANT USAGE ON WAREHOUSE PDM_DEMO_WH TO ROLE DEMO_PDM_ADMIN;
GRANT USAGE ON DATABASE PDM_DEMO TO ROLE DEMO_PDM_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PDM_DEMO TO ROLE DEMO_PDM_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PDM_DEMO.RAW TO ROLE DEMO_PDM_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PDM_DEMO.ANALYTICS TO ROLE DEMO_PDM_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PDM_DEMO.ML TO ROLE DEMO_PDM_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PDM_DEMO.APP TO ROLE DEMO_PDM_ADMIN;
GRANT CREATE TABLE ON SCHEMA PDM_DEMO.RAW TO ROLE DEMO_PDM_ADMIN;
GRANT CREATE TABLE ON SCHEMA PDM_DEMO.ANALYTICS TO ROLE DEMO_PDM_ADMIN;
GRANT CREATE TABLE ON SCHEMA PDM_DEMO.ML TO ROLE DEMO_PDM_ADMIN;
GRANT CREATE TABLE ON SCHEMA PDM_DEMO.APP TO ROLE DEMO_PDM_ADMIN;
GRANT CREATE VIEW ON SCHEMA PDM_DEMO.ANALYTICS TO ROLE DEMO_PDM_ADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA PDM_DEMO.ANALYTICS TO ROLE DEMO_PDM_ADMIN;
GRANT CREATE STAGE ON SCHEMA PDM_DEMO.APP TO ROLE DEMO_PDM_ADMIN;
GRANT READ, WRITE ON STAGE PDM_DEMO.APP.MODELS TO ROLE DEMO_PDM_ADMIN;
GRANT READ, WRITE ON STAGE PDM_DEMO.APP.DATA_STAGE TO ROLE DEMO_PDM_ADMIN;
GRANT READ, WRITE ON IMAGE REPOSITORY PDM_DEMO.APP.PDM_REPO TO ROLE DEMO_PDM_ADMIN;
GRANT CREATE SERVICE ON SCHEMA PDM_DEMO.APP TO ROLE DEMO_PDM_ADMIN;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE DEMO_PDM_ADMIN;
GRANT CREATE SNOWFLAKE.ML.MODEL ON SCHEMA PDM_DEMO.ML TO ROLE DEMO_PDM_ADMIN;

GRANT ROLE DEMO_PDM_ADMIN TO ROLE ACCOUNTADMIN;

SELECT 'Setup complete. Run seed_data.py next.' AS STATUS;
